### ISSUE TITLE
ERROR in TypeError / length

### ISSUE THREAD

**Issue by kamalkech** [hamedbaatour/angularfire-lite-demo#2]
```
Angular CLI: 1.6.3
Node: 8.9.1
OS: darwin x64
Angular: 5.1.2
NPM: 5.5.1
```

I get this error when try to run a demo :

```
ERROR in TypeError: Cannot read property 'length' of undefined
node_modules/typescript/lib/typescript.js:16640:110
node_modules/typescript/lib/typescript.js:16572:26
node_modules/typescript/lib/typescript.js:16521:26
```

**Comment by hamedbaatour** [comment]
@kamalkech Thank you for opening an issue but it is unfortunately missing a lot of details so can you at least provide a simple reproduction on Stackblitz?

**Comment by tdittmann** [comment]
I had the same error. It was because i forgot to add the file environment.prod.ts. So after you checked out the demo you have to create a dir called environment and add two files:
- environment.ts
- environment.prod.ts
... and don't forget your firebase settings ;)

**Comment by hamedbaatour** [comment]
@tdittmann thank you for pointing this out so @kamalkech you should add your own firebase project configuration file by copying it from the firebase dashboard and if you want to see how check the first part of my blog post on Medium here: [Angular 5 Server Side Rendering With Firebase 🔥 — Step-By-Step Guide](https://medium.com/@hamedbaatour/angular-5-server-side-rendering-with-firebase-step-by-step-guide-ec5f4d8ef38b)

**Comment by hsboykjh** [comment]
I have same issues when I clone and build this latest version of sources.

ERROR in TypeError: Cannot read property 'length' of undefined
at createSourceFile (/Users/jihoon/Documents/angular5-ssr/angularfire-lite/angularfire-lite-demo/node_modules/typescript/lib/typescript.js:16640:109)
at parseSourceFileWorker (/Users/jihoon/Documents/angular5-ssr/angularfire-lite/angularfire-lite-demo/node_modules/typescript/lib/typescript.js:16572:26)
at Object.parseSourceFile (/Users/jihoon/Documents/angular5-ssr/angularfire-lite/angularfire-lite-demo/node_modules/typescript/lib/typescript.js:16521:26)
at Object.createSourceFile (/Users/jihoon/Documents/angular5-ssr/angularfire-lite/angularfire-lite-demo/node_modules/typescript/lib/typescript.js:16371:29)
at VirtualFileStats.getSourceFile (/Users/jihoon/Documents/angular5-ssr/angularfire-lite/angularfire-lite-demo/node_modules//src/compiler_host.js:67:35)

@hamedbaatour I saw you added environment files recently but it should be moved to /src/environment :)
