### ISSUE TITLE
Errors when starting the project with SSR

### ISSUE THREAD

**Issue by billbarni** [hamedbaatour/angularfire-lite-demo#3]
1 - Cloned the repo.
2 - npm i
3 - Copy configs into environment.ts and relocate it to /src/
4 - npm run universal

I get this:

```
Node server listening on http://localhost:5000
Please add your own Firebase project configuration in app.module.ts
batched writes SSR is not supported yet
ERROR TypeError: Cannot read property 'set' of undefined
    at l.n.AppComponent.l.ngOnInit (C:\Users\William\Desktop\angularfire-lite-demo\dist\server.js:151722:14535)
    at checkAndUpdateDirectiveInline (C:\Users\William\Desktop\angularfire-lite-demo\dist\server.js:16415:19)
    at checkAndUpdateNodeInline (C:\Users\William\Desktop\angularfire-lite-demo\dist\server.js:17942:20)
    at checkAndUpdateNode (C:\Users\William\Desktop\angularfire-lite-demo\dist\server.js:17885:16)
    at prodCheckAndUpdateNode (C:\Users\William\Desktop\angularfire-lite-demo\dist\server.js:18609:5)
    at Object.updateDirectives (C:\Users\William\Desktop\angularfire-lite-demo\dist\server.js:151722:13454)
    at Object.updateDirectives (C:\Users\William\Desktop\angularfire-lite-demo\dist\server.js:18331:29)
    at Object.checkAndUpdateView (C:\Users\William\Desktop\angularfire-lite-demo\dist\server.js:17851:14)
    at ViewRef_.detectChanges (C:\Users\William\Desktop\angularfire-lite-demo\dist\server.js:15616:22)
    at C:\Users\William\Desktop\angularfire-lite-demo\dist\server.js:9923:63
ERROR HttpErrorResponse {
  headers:
   HttpHeaders {
     normalizedNames: Map {},
     lazyUpdate: null,
     lazyInit: [Function] },
  status: 401,
  statusText: 'Unauthorized',
  url: 'https://angularfire-lite-demo.firebaseio.com/hello.json',
  ok: false,
  name: 'HttpErrorResponse',
  message: 'Http failure response for https://angularfire-lite-demo.firebaseio.com/hello.json: 401 Unauthorized',
  error: { error: 'Permission denied' } }
ERROR HttpErrorResponse {
  headers:
   HttpHeaders {
     normalizedNames: Map {},
     lazyUpdate: null,
     lazyInit: [Function] },
  status: 401,
  statusText: 'Unauthorized',
  url: 'https://angularfire-lite-demo.firebaseio.com/hello/hello.json',
  ok: false,
  name: 'HttpErrorResponse',
  message: 'Http failure response for https://angularfire-lite-demo.firebaseio.com/hello/hello.json: 401 Unauthorized',
  error: { error: 'Permission denied' } }
ERROR HttpErrorResponse {
  headers:
   HttpHeaders {
     normalizedNames: Map {},
     lazyUpdate: null,
     lazyInit: [Function] },
  status: 401,
  statusText: 'Unauthorized',
  url: 'https://angularfire-lite-demo.firebaseio.com/hello.json?&limitToLast=1&orderBy=%22$key%22',
  ok: false,
  name: 'HttpErrorResponse',
  message: 'Http failure response for https://angularfire-lite-demo.firebaseio.com/hello.json?&limitToLast=1&orderBy=%22$key%22: 401 Unauthorized',
  error: { error: 'Permission denied' } }
ERROR HttpErrorResponse {
  headers:
   HttpHeaders {
     normalizedNames: Map {},
     lazyUpdate: null,
     lazyInit: [Function] },
  status: 404,
  statusText: 'Not Found',
  url: 'https://firestore.googleapis.com/v1beta1/projects/angularfire-lite-demo/databases/(default)/documents/hello/hellodoc',
  ok: false,
  name: 'HttpErrorResponse',
  message: 'Http failure response for https://firestore.googleapis.com/v1beta1/projects/angularfire-lite-demo/databases/(default)/documents/hello/hellodoc: 404 Not Found',
  error:
   { error:
      { code: 404,
        message: 'Document "projects/angularfire-lite-demo/databases/(default)/documents/hello/hellodoc" not found.',
        status: 'NOT_FOUND' } } }
ERROR TypeError: Cannot read property 'forEach' of undefined
    at MapSubscriber.project (C:\Users\William\Desktop\angularfire-lite-demo\dist\server.js:152562:35)
    at MapSubscriber._next (C:\Users\William\Desktop\angularfire-lite-demo\dist\server.js:130642:35)
    at MapSubscriber.Subscriber.next (C:\Users\William\Desktop\angularfire-lite-demo\dist\server.js:21399:18)
    at MapSubscriber._next (C:\Users\William\Desktop\angularfire-lite-demo\dist\server.js:130648:26)
    at MapSubscriber.Subscriber.next (C:\Users\William\Desktop\angularfire-lite-demo\dist\server.js:21399:18)
    at FilterSubscriber._next (C:\Users\William\Desktop\angularfire-lite-demo\dist\server.js:130552:30)
    at FilterSubscriber.Subscriber.next (C:\Users\William\Desktop\angularfire-lite-demo\dist\server.js:21399:18)
    at MergeMapSubscriber.notifyNext (C:\Users\William\Desktop\angularfire-lite-demo\dist\server.js:73077:30)
    at InnerSubscriber._next (C:\Users\William\Desktop\angularfire-lite-demo\dist\server.js:129892:21)
    at InnerSubscriber.Subscriber.next (C:\Users\William\Desktop\angularfire-lite-demo\dist\server.js:21399:18)
ERROR TypeError: Cannot read property 'fields' of undefined
    at _loop_1 (C:\Users\William\Desktop\angularfire-lite-demo\dist\server.js:152693:46)
    at MapSubscriber.project (C:\Users\William\Desktop\angularfire-lite-demo\dist\server.js:152702:25)
    at MapSubscriber._next (C:\Users\William\Desktop\angularfire-lite-demo\dist\server.js:130642:35)
    at MapSubscriber.Subscriber.next (C:\Users\William\Desktop\angularfire-lite-demo\dist\server.js:21399:18)
    at MapSubscriber._next (C:\Users\William\Desktop\angularfire-lite-demo\dist\server.js:130648:26)
    at MapSubscriber.Subscriber.next (C:\Users\William\Desktop\angularfire-lite-demo\dist\server.js:21399:18)
    at FilterSubscriber._next (C:\Users\William\Desktop\angularfire-lite-demo\dist\server.js:130552:30)
    at FilterSubscriber.Subscriber.next (C:\Users\William\Desktop\angularfire-lite-demo\dist\server.js:21399:18)
    at MergeMapSubscriber.notifyNext (C:\Users\William\Desktop\angularfire-lite-demo\dist\server.js:73077:30)
    at InnerSubscriber._next (C:\Users\William\Desktop\angularfire-lite-demo\dist\server.js:129892:21)
https://github.com/hamedbaatour/angularfire-lite-demo/issues/new

```

**Comment by hamedbaatour** [comment]
why did you relocate the environment folder to the src folder of the project?
please keep it in the root of the project and just add your firebase project configuration to the config object inside both `environment./environment.prod.ts` and  `environment./environment.ts`.
if you still face any issues please feel free to reopen the issue and provide a link to a reproduction repo.
